apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-extended.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: tests-api
  name: tests-api
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 5000
  type: LoadBalancer
  selector:
    io.kompose.service: tests-api
