apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-extended.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: tests-api
  name: tests-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tests-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-extended.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: tests-api
    spec:
      containers:
        - env:
            - name: AI__URL
              value: https://api.proxyapi.ru/openai/v1
            - name: AI__key
              value: sk-zfUgzzqzR0Sh9tTc1uXr73eAJmUtEG6v
            - name: AI__version
              value: gpt-4o-mini
            - name: Authorization__URL
              value: http://authorization-api:8005/validate
            - name: ConnectionStrings__DefaultConnection
              value: Host=db; Port=5444; Database=AITests; Username=AITests; Password=1qaz2wsx
          image: tests-api
          imagePullPolicy: Never    
          name: tests-api
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
