version: "3.9"
services:
  api:
    restart: always
    build:
      context: .
    ports:
      - "8000:5000"
    environment:
      "AI:URL": "${URL}"
      "AI:key": "${key}"
      "AI:version": "${version}"